# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Les Festi'Routils 2017
email: lesfestiroutils@yahoo.fr
description: > # this means to ignore newlines until "baseurl:"
  Festival de musiques du monde dans une ambiance très familiale.
  Une programmation toujours très variée, mélangeant les styles et
  les genres.
baseurl: # the subpath of your site, e.g. /blog
url: "https://eml-trm.github.io/lesfestiroutils/" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  editions:
    output: true
  album_2011:
    output: true
  album_2012:
    output: true
  album_2013:
    output: true
  album_2015:
    output: true
  album_2016:
    output: true



# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
